/**
 * API Service Configuration
 * 
 * This file configures the axios instance for API calls.
 * The actual API client is generated by openapi-generator-cli
 * Run `npm run gen:api` to generate the API client from the OpenAPI spec.
 */

import axios from 'axios';

// Get base URL from environment variables
const baseURL = import.meta.env.VITE_API_BASE_URL || 'https://pawplanet-ae61a47d7179.herokuapp.com';

// Create axios instance with default configuration
export const apiClient = axios.create({
  baseURL,
  timeout: 10000,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor for adding auth token
apiClient.interceptors.request.use(
  (config) => {
    // Check both sessionStorage and localStorage for auth token
    const token = sessionStorage.getItem('authToken') || localStorage.getItem('authToken');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
      console.log(`API Request: ${config.method?.toUpperCase()} ${config.url} - Token attached`);
    } else {
      console.log(`API Request: ${config.method?.toUpperCase()} ${config.url} - No token found`);
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response interceptor for error handling
apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      // Handle unauthorized access - clear both storage types
      localStorage.removeItem('authToken');
      sessionStorage.removeItem('authToken');
      window.location.href = '/login';
    }
    return Promise.reject(error);
  }
);

export default apiClient;
