/**
 * API Service Configuration
 * 
 * This file configures the axios instance for API calls.
 * The actual API client is generated by openapi-generator-cli
 * Run `npm run gen:api` to generate the API client from the OpenAPI spec.
 *
 * Features:
 * - Automatic JWT token attachment to requests
 * - Automatic token refresh on 401 errors
 * - Request queueing during token refresh
 * - Prevents infinite loops on auth endpoints
 */

import axios, { AxiosError, InternalAxiosRequestConfig } from 'axios';

// Get base URL from environment variables
const baseURL = import.meta.env.VITE_API_BASE_URL || 'https://pawplanet-ae61a47d7179.herokuapp.com';

// Create axios instance with default configuration
export const apiClient = axios.create({
  baseURL,
  timeout: 10000,
  headers: {
    'Content-Type': 'application/json',
  },
});

// ============================================================================
// TOKEN REFRESH STATE MANAGEMENT
// ============================================================================

let isRefreshing = false;
let failedQueue: Array<{
  resolve: (token: string) => void;
  reject: (error: Error | AxiosError) => void;
}> = [];

/**
 * Process all queued requests after token refresh completes
 */
const processQueue = (error: Error | AxiosError | null, token: string | null = null) => {
  failedQueue.forEach(promise => {
    if (error) {
      promise.reject(error);
    } else if (token) {
      promise.resolve(token);
    }
  });
  failedQueue = [];
};

/**
 * Get current auth token from storage
 */
const getToken = (): string | null => {
  return sessionStorage.getItem('authToken') || localStorage.getItem('authToken');
};

/**
 * Save new token to storage (maintains original storage location)
 */
const saveToken = (token: string) => {
  // Save to localStorage if it was there before, otherwise sessionStorage
  if (localStorage.getItem('authToken')) {
    localStorage.setItem('authToken', token);
  } else {
    sessionStorage.setItem('authToken', token);
  }
};

/**
 * Clear all auth tokens from storage
 */
const clearTokens = () => {
  localStorage.removeItem('authToken');
  sessionStorage.removeItem('authToken');
};

/**
 * Refresh the authentication token using the refresh token API
 * @returns Promise with new token
 * @throws Error if refresh fails
 */
const refreshAuthToken = async (): Promise<string> => {
  const currentToken = getToken();
  if (!currentToken) {
    throw new Error('No token available to refresh');
  }

  try {
    console.log('🔄 Calling refresh token API...');

    // Call refresh token API endpoint
    const response = await axios.post(
      `${baseURL}/api/v1/auth/refresh`,
      { token: currentToken },
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );

    // Extract new token from response
    const newToken = response.data?.result?.token;
    if (!newToken) {
      throw new Error('No token in refresh response');
    }

    // Save new token to storage
    saveToken(newToken);
    console.log('✅ Token refreshed successfully');

    return newToken;
  } catch (error) {
    console.error('❌ Token refresh failed:', error);
    throw error;
  }
};

// ============================================================================
// REQUEST INTERCEPTOR
// ============================================================================

apiClient.interceptors.request.use(
  (config) => {
    const token = getToken();
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
      console.log(`📤 API Request: ${config.method?.toUpperCase()} ${config.url} - Token attached`);
    } else {
      console.log(`📤 API Request: ${config.method?.toUpperCase()} ${config.url} - No token`);
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// ============================================================================
// RESPONSE INTERCEPTOR WITH AUTOMATIC TOKEN REFRESH
// ============================================================================

apiClient.interceptors.response.use(
  (response) => response,
  async (error: AxiosError) => {
    const originalRequest = error.config as InternalAxiosRequestConfig & { _retry?: boolean };

    // Only handle 401 Unauthorized errors
    if (error.response?.status !== 401) {
      return Promise.reject(error);
    }

    console.log('🔒 401 Unauthorized - Token may be expired');

    // Don't retry auth endpoints to prevent infinite loops
    const isAuthEndpoint =
      originalRequest.url?.includes('/auth/login') ||
      originalRequest.url?.includes('/auth/register') ||
      originalRequest.url?.includes('/auth/refresh') ||
      originalRequest.url?.includes('/auth/logout');

    if (isAuthEndpoint) {
      console.log('🚫 Auth endpoint failed - not retrying');
      clearTokens();
      window.location.href = '/login';
      return Promise.reject(error);
    }

    // Don't retry if already attempted
    if (originalRequest._retry) {
      console.log('🚫 Already retried - redirecting to login');
      clearTokens();
      window.location.href = '/login';
      return Promise.reject(error);
    }

    // If token refresh is already in progress, queue this request
    if (isRefreshing) {
      console.log('⏳ Token refresh in progress - queueing request');
      return new Promise((resolve, reject) => {
        failedQueue.push({
          resolve: (token: string) => {
            originalRequest.headers.Authorization = `Bearer ${token}`;
            resolve(apiClient(originalRequest));
          },
          reject: (err: Error | AxiosError) => {
            reject(err);
          },
        });
      });
    }

    // Mark request as retrying and start token refresh
    originalRequest._retry = true;
    isRefreshing = true;

    try {
      // Attempt to refresh the token
      const newToken = await refreshAuthToken();

      // Update the failed request with new token
      originalRequest.headers.Authorization = `Bearer ${newToken}`;

      // Process all queued requests with new token
      processQueue(null, newToken);

      // Retry the original request
      console.log('🔄 Retrying original request with new token');
      return apiClient(originalRequest);
    } catch (refreshError) {
      // Token refresh failed - clear auth and redirect to login
      console.error('❌ Token refresh failed - logging out');
      processQueue(refreshError as Error | AxiosError, null);
      clearTokens();
      window.location.href = '/login';
      return Promise.reject(refreshError);
    } finally {
      isRefreshing = false;
    }
  }
);

export default apiClient;
