/* tslint:disable */
/* eslint-disable */
/**
 * PawPlanet API
 * PawPlanet Backend API - Social network for pets
 *
 * The version of the OpenAPI document: v1
 * Contact: support@pawplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

